# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('publish_date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
    ]
