# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='age',
            new_name='int',
        ),
    ]
